title: Archilocus
description: > # this means to ignore newlines until "baseurl:"
  La place des architectes IT
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.archilocu.tech" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2022_pages', '_2021_pages', '_2021_06_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty
